printf "\e[1;95m                             ______           \e[0m\n"
printf "\e[1;95m                          .-        -.         \e[0m\n"
printf "\e[1;95m                         /    Andz    \         \e[0m\n"
printf "\e[1;95m                           ---------             \e[0m\n"
printf "\e[1;95m                        |,  .-.  .-.  ,|         \e[0m\n" 
printf "\e[1;77m                        | )(_ /  \_ )( |             \e[0m\n"
printf "\e[1;77m                        |/     /\     \|               \e[0m\n"
printf "\e[1;91m              (@_       <__    ^^    __>                          \e[0m\n"
printf "\e[1;91m         _     ) \_______\__|IIIIII|__/_________________________________________\\   \e[0m\n"
printf "\e[1;91m        (_)@8@8{}<_________THANK FOR USING______________________________________//    \e[0m\n"
printf "\e[1;91m               )_/         \ IIIIII /                                  \e[0m\n"
printf "\e[1;91m              (@            --------                                   \e[0m\n"
